import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar/navbar'
import Modal from './components/modal/Modal'
import CreateStoreModal from './components/modal/CreateStoreModal'
import Provider from '@/providers/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          {/* <Navbar /> */}
          sdfsdf
          <CreateStoreModal />

          {children}
        </Provider>
      </body>
    </html>
  )
}
